freebsd_task:
  freebsd_instance:
    image_family: freebsd-14-0
  install_script: |
    pkg install -y cmake
    pw groupadd testgrp
    pw useradd testuser -g testgrp -w none -m
    chown -R testuser:testgrp .
  build_script: |
    sudo -u testuser .ci/unix-build.sh
  test_script: |
    sudo -u testuser .ci/unix-test.sh

rockylinux8_task:
  container:
    image: docker.io/rockylinux:8
  install_script: |
    dnf group install -y "Development Tools"
    dnf install cmake -y
  build_script: |
    .ci/unix-build.sh
  test_script: |
    .ci/unix-test.sh

rockylinux9_task:
  container:
    image: docker.io/rockylinux:9
  install_script: |
    dnf group install -y "Development Tools"
    dnf install cmake -y
  build_script: |
    .ci/unix-build.sh
  test_script: |
    .ci/unix-test.sh
